name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_magishrms:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'magishrms' }}
      run: |
        cd ./aspnet-core
        docker login --username=_ --password=$HEROKU_API_KEY --password-stdin registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
